### ISSUE TITLE
Modifier un employé/client

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#10]

**Comment by ymei2296236** [comment]
**Charte graphique (Xuying)**

**Comment by 2296789** [comment]
- [ ] Concevoir la page d'ajouter ou midiifier un ciient (1.5h)
- [ ] Charte graphique pour 3 Versions de la page d'ajouter ou midiifier un ciient (0.5)
- [ ] Concevoir la page d'ajouter ou midiifier un employé (0.5)
- [ ] Charte graphique pour 3 Versions de la page d'ajouter ou midiifier un employé (0.25)

**Comment by guillovilla** [comment]
- [ ] Créer les formulaires HTML nécessaires pour saisir les nouvelles informations de l'employé/client. (2h)
- [ ] Appliquer le style CSS pour rendre les formulaires attrayants et conviviaux. (3h)
- [ ] Mettre en place la logique côté serveur pour gérer la modification des données de l'employé/client. (3h)
