### ISSUE TITLE
Supprimer un employé/client

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#11]

**Comment by ymei2296236** [comment]
**Charte graphique (Xuying)**

**Comment by 2296789** [comment]
- [ ] Concevoir la page de liste de ciient (1.5h)
- [ ] Charte graphique pour 3 Versions de la page de liste de ciient (0.5)
- [ ] Concevoir la page de liste d'employé (0.5h)
- [ ] Charte graphique pour 3 Versions de la page de liste d'employé  (0.25h)

**Comment by guillovilla** [comment]
- [ ] Créer un form (bouton) de suppression pour éviter les suppressions accidentelles.(1h)
- [ ] Créer un message de confirmatoin pour éviter les suppressions accidentelles.(1.5h)
- [ ] Appliquer le style CSS. (0.25h)
- [ ] Mettre en place la logique côté serveur pour gérer la suppression de l'employé/client.
- [ ] Tester la fonctionnalité de suppression.(0.5)
- [ ] S'assurer que seuls les utilisateurs autorisés ont accès à la fonction de suppression.(0.5h)
