### ISSUE TITLE
Trier les voitures par constructeur, année, modèle etc

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#14]

**Comment by ymei2296236** [comment]
- [ ] Créer le formulaire de tri (0.5h)
- [ ] Trier les voiture par constructeur (0.5h)
- [ ] Trier les voiture par année (0.5h)
- [ ] Trier les voiture par modèle (0.5h)
- [ ] Trier les voiture par combinaison de conditions (1h)
