### ISSUE TITLE
Rechercher les voitures par construteur, année, modèle

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#15]

**Comment by guillovilla** [comment]
- [ ] Mettre en place un champ de texte pour rechercher des voitures dans la base de données.  (0.25h)    
- [ ] Créer un élément d'entrée de texte dans l'interface utilisateur.  (0.25h)  
- [ ] Rédiger des requêtes SQL pour récupérer des données de la base de données en fonction de l'entrée de l'utilisateur. (1.5h)  
- [ ] Développer la logique de recherche dans la base de données.  (1.5h)  
- [ ] Concevoir la logique  JavaScript pour gérer la recherche de voitures.  (8h)  
- [ ] Connecter la logique de recherche à l'interface utilisateur pour afficher les résultats. (4h)
