### ISSUE TITLE
Ajouter une ou plusieurs voiture au panier pour un retrait ou pour l'acheter 

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#16]

**Comment by ymei2296236** [comment]
**Frontend (Xuying)** 

- [ ] Créer la page de panier (0.5h)
- [ ]  Faire la traduction sur la page de panier (0.5h)
- [ ]  Créer le fichier de style pour la page de panier pour être responsive à travers les trois types d'écran (1.5h)

**Comment by ymei2296236** [comment]
**Conception graphique (Xuying)**

- [ ] Concevoir la page de commande d'achat (3 parties : confirmer les informations relatives à la commande, remplir les informations relatives au client, choisir la méthode d'expédition) (4h)
- [ ]  3 Versions de la page de commande d'achat (2h)
- [ ]  Concevoir la page de paiement (3h)
- [ ]  3 Versions de la page de paiement (1h)

**Comment by 2296789** [comment]
- [ ]  Concevoir la page de panier (3h)
- [ ]  Charte graphique pour 3 Versions de la page de panier (1h)

**Comment by fermamud** [comment]
**Backend codage (Fernanda)**

- [ ] Gestion d'ajout de voiture au panier
- [ ] Affichage de panier
- [ ] Gestion de redirection vers reservation ou achat
