### ISSUE TITLE
Payer une commande

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#19]

**Comment by ymei2296236** [comment]
- [ ]  Créer la page de paiement et le formulaire d'ajout de paiement  (1h)
- [ ]  Valider le formulaire d'ajout de paiement  et afficher les message d'erreurs (1h)
- [ ]  Insérer le paiement en base de données (1h)
- [ ]  Faire la traduction (0.5h)
- [ ]  Créer le fichier de style pour être responsive à travers les trois types d'écran (1.5h)
- [ ]  Tester la page (1h)

**Comment by ymei2296236** [comment]
**Charte graphique (Xuying)**

**Comment by 2296789** [comment]
- [ ]  Concevoir la page de liste de commande (3h)
- [ ]  Charte graphique pour 3 Versions de la page de liste de commande (1h)
