### ISSUE TITLE
Afficher la description de l'entreprise

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#21]

**Comment by 2296789** [comment]
- [ ] Faire rechercher pour la description de l'entreprise (1h)
- [ ] Concevoir la page de la description de l'entreprise  (1h)
- [ ] Chart graphique pour 3 versions de la page de la description de l'entreprise (0.5h)
- [ ]  Créer la structure HTML (1.5h)
- [ ]  Appliquer le style CSS (1.5h)
