### ISSUE TITLE
Afficher le bord de journal

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#31]

**Comment by fermamud** [comment]
Low priority

**Comment by guillovilla** [comment]
- [ ] Concevoir l'interface utilisateur pour afficher le bord de journal. (2h)
- [ ] Concevoir et ajouter des éléments d'interface utilisateur pour afficher les détails des journaux.(2h)
- [ ] Mettre à jour la logique de l'application pour récupérer et afficher les journaux.(2h)
- [ ] Mettre en œuvre la récupération des données de journal depuis la base de données.(2h)
- [ ] Mettre à jour l'interface utilisateur pour afficher les journaux récupérés.(2h)
