### ISSUE TITLE
Afficher la page de commande

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#48]

**Comment by fermamud** [comment]
**Front-end - Xuying**

**Comment by fermamud** [comment]
**Back-end - Fernanda**

**Comment by 2296789** [comment]
- [ ] Faire rechercher pour la page de commande (1h)
- [ ] Concevoir la page de la page de commande  (1h)
- [ ] Chart graphique pour 3 versions de la page de commande (0.5h)
- [ ]  Créer la structure HTML (1.5h)
- [ ]  Appliquer le style CSS (1.5h)
