### ISSUE TITLE
Gestion d'affichage quand la voiture est réservée

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#50]

**Comment by guillovilla** [comment]
- [ ] Concevoir et ajouter un élément d'interface utilisateur pour afficher l'état de réservation. (0.25)
- [ ] Mettre à jour la logique de l'interface utilisateur pour afficher un message approprié lorsque la voiture est réservée. (0.25)
- [ ] Effectuer des tests pour vérifier que le message d'état de réservation est correctement affiché. (0.25)
