### ISSUE TITLE
Gestion des images

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#57]
**Mei**

- [x] Affichage des photos d'une voiture, ajout des photos, suppression des photos, setter la photo principale (5)
- [x] Mise à jour le formulaire d'ajout et de modification de voiture (0.5h)
- [x] Gestion CSS (espaces pour 10 images) et position des images (1h)
- [x] Compression et redimensionner des images (3h)
- [ ] Gestion d'orientation : une fonctionnalité nécessaire, parce que si une réorientation n'effectue pas une modification de BD, la réorientation est temporaire. Si cela doit envoyer une requête pour modifier la photo, ça sera plus facile de la supprimer et téléverver de nouveau.    
- [x] Test (2h)

**Comment by fermamud** [comment]
**Fernanda**

- [ ] Mettre a jour formulaire
- [ ] Mettre a jour controlleur
- [ ] Mettre a jour model

**Comment by ymei2296236** [comment]
Si la gestion d'images ne fonctionne pas sur votre ordinateur, essayez les solutions suivantes :

1. Changer la limite de taille de fichiers à téléviser : 
Dans fichier php.ini, changer 'post_max_size' et 'upload_max_filesize' aux ces valeurs
post_max_size = 60M
upload_max_filesize = 5M

2. Activer php gd extension
- Dans fichier php.ini, rechercher ';extension=gd'
- Supprimer le ';' devant  'extension=gd'
- Redémarrer php ou l'ordinateur

3. Installer Scoop
https://scoop.sh

4. Installer spatie/image-optimizer Image package
- Ouvrir Terminal/Powershell/Bash
- Entrer 'composer require spatie/image-optimizer'

5. Installer intervention/image
- Entrer 'composer require intervention/image'

6. Installer optimizers de différentes types de photo (si un de ces optimizers n'existe pas, c'est pas grave)
- Ouvrir Terminal/Powershell/Bash
- Entrer 'scoop install jpegoptim'
- Entrer 'scoop install optipng'
- Entrer 'scoop install pngquant'
- Entrer 'npm install -g svgo@1.3.2'
- Entrer 'scoop install gifsicle'
- Entrer 'scoop install webp'


Référence: 
https://www.prashantwebdeveloper.in/laravel-image-compression-project/
https://image.intervention.io/v3/introduction/installation
