### ISSUE TITLE
Gestion URL pour recherche

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#58]
**Mei**

- [ ] Changer filtrage de PHP avec JS (low priority)

**Comment by fermamud** [comment]
**Guillermo**

- [ ] Gestion de changement d'URL

**Comment by guillovilla** [comment]
- [ ] Capturer les paramètres d'URL dans l'interface utilisateur.  (2h)
- [ ] Mettre à jour la logique de recherche pour utiliser les paramètres d'URL. (5h)
