### ISSUE TITLE
Afficher la page de produit/voiture

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#6]

**Comment by ymei2296236** [comment]
- [ ] Créer la page de voiture et le formulaire d'ajout de la voiture (1h)
- [ ] Valider le formulaire d'ajout de la voiture et afficher les message d'erreurs (1h)
- [ ] Insérer la voiture en base de données et rediriger la page (1h)
- [ ] Faire la traduction sur la page de voiture (0.5h)
- [ ] Créer le fichier de style pour la page de voiture pour être responsive à travers les trois types d'écran (1.5h)
- [ ] Tester la page de voiture (1h)
