### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#60]
**Xuying**

- [x] Gestion CSS / HTML
- [x] Design

**Comment by fermamud** [comment]
- [ ] Gestion CSS / HTML
- [ ] Gestion route

**Comment by 2296789** [comment]
- [ ] Créer une image 404 correspondant au logo et produire le fichier svg (1h)
- [ ] Concevoir la page (0.5h)
- [ ] Chart graphique pour 3 versions (0.5h)
- [ ] Créer la structure HTML (0.5h)
- [ ] Appliquer le style CSS (0.5h)
