### ISSUE TITLE
Guest checkout

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#61]

**Comment by 2296789** [comment]
- [ ]  Concevoir la page (1h)
- [ ]  Chart graphique pour 3 versions (0.5h)
- [ ]  Créer la structure HTML (1h)
- [ ]  Appliquer le style CSS (1h)

**Comment by fermamud** [comment]
- [ ] Calculer les taux d'impot provinciaux en fonction du choix d'expédition (2h)
- [ ] Mise à jour du tableau commande_taxes (1h)
- [ ] Envoyer les informations nécessaires pour finaliser le paiement (1.5h)
