### ISSUE TITLE
Ajouter une voiture avec paramètres de la voiture

### ISSUE THREAD

**Issue by fermamud** [582-41E-MA/projet-web-2#9]

**Comment by fermamud** [comment]
- [ ] Charte graphique : 3 Versions de la page d'ajouter une voiture (CRM) (1h)

**Comment by fermamud** [comment]
- [ ] Frontend form

**Comment by fermamud** [comment]
[ ] Backend codage

**Comment by fermamud** [comment]
> **Frontend form (Xuying ) **
> 
> * [ ]   Créer la page des paramètres de la voiture (0.5h)
> * [ ]   Faire la traduction sur la page des paramètres de la voiture (0.5h)
> * [ ]   Créer le fichier de style pour la page des paramètres de la voiture (3 tailles) (1.5h)
> * [ ]  Tester la page (0.75h)
> 
> **Frontend form (Mei) **
> 
> * [ ]   Créer la page de voiture (0.25h)
> * [ ]   Faire la traduction sur la page de voiture (0.5h)
> * [ ]   Créer le fichier de style pour la page de voiture (3 tailles)  (0.25h)

@ymei2296236 Ne vous inquiétez pas de la traduction de la page d'ajout de voiture, je suis déjà en train de le faire pendant que je travaille sur le backend de la page.

**Comment by 2296789** [comment]
- [x]  Concevoir la page des paramètres de la voiture (3h) 
- [x]  Charte graphique pour 3 Versions (1.5h)
